# Generated by Django 4.0 on 2022-02-06 12:22

import accounts.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, validators=[accounts.validate.validate_age], verbose_name='年齢'),
        ),
    ]
